### ISSUE TITLE
Can Players choose their own Dice colors for Hope and Fear?

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#13]
Players should be able to choose dice colors

**Comment by ComfortableGreySloth** [comment]
Sort of. The Dice so Nice! Module does allow people to change their colors, but it in no way allows the Hope and Fear dice to be different colors. Conversely, the current macro overwrites it for the given colors. I'm closing this issue, it is way above the scope of this Simple Worldbuilding hack.
