### ISSUE TITLE
All Item descriptions in chat to have clickable macros where possible

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#15]
Try and have all item descriptions appear in chat with clickable macros so that there is no need to open up the item description from character sheet to trigger things

**Comment by ComfortableGreySloth** [comment]
I like this one. Partially implemented, but I will close this issue and say it's implemented. Just a matter of manually going through and adding the macros. I'm using the language of "Un/Mark Hope/HP/Stress"
