### ISSUE TITLE
Auto-calc Succes/Failure for Action Rolls

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#6]
1. User targets adversary and makes an action roll
2. The dialog asks the user whether they want to roll adv/disadv/normal AS WELL AS if they want to add a modifier to the roll (GM to advise). 
3. The roll is made and considers the Adversary's difficulty and the modifier entered to return a Success/Fail result as part of the result output.

**Comment by ComfortableGreySloth** [comment]
Only works when targeting somebody, but it works.
