### ISSUE TITLE
Incorporate Zhell duality dice roll result display

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#8]
Check out this duality dice macro from Zhell in Foundry? He's one of the Foundry community coding gurus. 

https://www.reddit.com/r/daggerheart/comments/1begqbf/foundry_macro_to_roll_duality_dice/

The roll and result card display look better in chat. (see screenshot - rolls in one card, as opposed to the 3-card split with the current approach).

![image](https://github.com/ComfortableGreySloth/FoundryVTTDaggerheartSWB/assets/16144202/2a2695f6-a028-4d88-a958-df8ecb82c33d)

**Comment by ComfortableGreySloth** [comment]
Thanks for linking their macro, I was having no luck merging (or hiding) the dice rolls in chat! This is very cool, would love to implement this.
