### ISSUE TITLE
L2 Domain Cards ready for adding to world

### ISSUE THREAD

**Issue by k2nair** [ComfortableGreySloth/FoundryVTTDaggerheartSWB#9]
I've written in some of the Item Macro descriptions that I can't figure out the next steps. Please check and update.

**Comment by k2nair** [comment]
Here's the zip folder.
[items.zip](https://github.com/ComfortableGreySloth/FoundryVTTDaggerheartSWB/files/15448877/items.zip)

**Comment by ComfortableGreySloth** [comment]
Thank you! Added.
